# Contraceptive Coach Skip Pattern 1
btn_confirm = "//android.widget.Button[@content-desc='Confirm']"
username = "//android.widget.EditText[@text='Phone No Or Email']"
password = "//android.widget.EditText[@text='Password']"
btn_sign_in = "//android.widget.Button[@content-desc='Sign in']"
btn_app = "//android.widget.TextView[@content-desc='COCO']"
session = "//android.widget.ImageView[@content-desc='Session']"
btn_skip = "//android.widget.Button[@content-desc='Skip the tutorial']"
startsession = "//android.widget.Button[@content-desc='Start session']"
birthyear = "//android.widget.EditText[@text='YYYY']"
current_student = "//android.view.View[@content-desc='Give the information below What year were you born? Are you currently a student? Yes No What is the highest level of education you have completed?']/android.widget.CheckBox[2]"
choose = "//android.widget.Button[@content-desc='Choose']"
degree = "//android.view.View[@content-desc='Completed a university degree or more']"
startsession2 = "//android.widget.Button[@content-desc='Start Session']"
q1_no = "//android.view.View[@content-desc='Have you ever had sex?']/android.widget.ImageView[4]"
q1_next = "//android.widget.Button[@content-desc='Next']"
q6_now = "//android.widget.RadioButton[@content-desc='Now']"
q6_next = "//android.widget.Button[@content-desc='Next']"
q8_1_seek = "//android.widget.SeekBar[@content-desc='52%']"
q8_next = "//android.widget.Button[@content-desc='Next']"
